apiVersion: v2
description: "ChemScraper Frontend"
name: chemscraper-frontend
version: 1.0.0
dependencies:
- name: common
  version: ~2.2.0
  repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
